---
app_name:
aws:
  access_key:
  secret_key:
  owner_id:
  region:
ebs:
  volume_id:
  description:
ami:
  regist_key:
s3:
  bucket:
gmail:
  from:
  to:
  password:
mysql:
  database:
  username:
  password:
  host:
