---
app_name:
aws:
  access_key:
  secret_key:
  owner_id:
  region:
ebs:
  volume_id:
  description:
ami:
  regist_key:
s3:
  bucket:
mail:
  from:
  to:
  address:
  user_name:
  password:
  port: 587

mysql:
  database:
  username:
  password:
  host:
